# Generated by Django 3.2.5 on 2021-07-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_enquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
