# Generated by Django 3.2.5 on 2021-07-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['time']},
        ),
    ]
