# Generated by Django 3.2.5 on 2021-08-01 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210801_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.enquiry')),
            ],
        ),
    ]
